/** Learn module mock categories and scheduling services for the unified catalog. */

import type {
  GradeLevel,
  LearningFormat,
  ProgramTerm,
  SchedulingCategory,
  SchedulingService,
  SchedulingServiceType,
  SubjectArea,
} from '@/lib/types'
import { EventBookingScheduleModeEnum } from '@/lib/types'

/** Shared mock program window — aligns learn services and generated slots for QA. */
export const LEARN_MOCK_PROGRAM_START_DATE = '2026-06-16' as const
export const LEARN_MOCK_PROGRAM_END_DATE = '2026-08-28' as const

interface LearnServiceSeed {
  readonly id: string
  readonly categoryId: string
  readonly serviceType: SchedulingServiceType
  readonly name: string
  readonly description: string
  readonly gradeLevel: GradeLevel
  readonly subjectArea: SubjectArea
  readonly learningFormat: LearningFormat
  readonly programTerm: ProgramTerm
  readonly programYear: number
  readonly programStartDate: string
  readonly programEndDate: string
  readonly instructorName: string
  readonly basePrice: number
  readonly capacity: number
  readonly durationMinutes: number
  readonly schedule: { dayOfWeek: string; startTime: string; endTime: string }[]
  readonly trialSessionAvailable?: boolean
  readonly trialSessionPrice?: number
  readonly imageUrl?: string
}

export const learnSchedulingCategories: SchedulingCategory[] = [
  {
    id: 'cat-learn-elementary',
    name: 'Elementary (K–5)',
    icon: 'BookOpen',
    displayOrder: 27,
    isActive: true,
    catalogSlug: 'learn',
    description: 'Phonics, math foundations, handwriting, and homework support.',
    requiresAttendee: false,
    membersOnly: false,
    allowFamilyMember: true,
    specialInstructionsEnabled: true,
    waitlistEnabled: true,
  },
  {
    id: 'cat-learn-middle',
    name: 'Middle School (6–8)',
    icon: 'Calculator',
    displayOrder: 28,
    isActive: true,
    catalogSlug: 'learn',
    description: 'Pre-algebra, essay writing, science, and executive functioning.',
    requiresAttendee: false,
    membersOnly: false,
    allowFamilyMember: true,
    specialInstructionsEnabled: true,
    waitlistEnabled: true,
  },
  {
    id: 'cat-learn-high-school',
    name: 'High School (9–12)',
    icon: 'GraduationCap',
    displayOrder: 29,
    isActive: true,
    catalogSlug: 'learn',
    description: 'STEM, humanities, and foreign language tracks.',
    requiresAttendee: false,
    membersOnly: false,
    allowFamilyMember: true,
    specialInstructionsEnabled: true,
    waitlistEnabled: true,
  },
  {
    id: 'cat-learn-test-prep-college',
    name: 'College Entrance Test Prep',
    icon: 'FileText',
    displayOrder: 30,
    isActive: true,
    catalogSlug: 'learn',
    description: 'SAT/ACT bootcamps and college essay workshops.',
    requiresAttendee: false,
    membersOnly: false,
    allowFamilyMember: true,
    specialInstructionsEnabled: true,
    waitlistEnabled: true,
  },
  {
    id: 'cat-learn-test-prep-private-school',
    name: 'Private School Admissions',
    icon: 'School',
    displayOrder: 31,
    isActive: true,
    catalogSlug: 'learn',
    description: 'ISEE, SSAT, HSPT, and COOP entrance exam prep.',
    requiresAttendee: false,
    membersOnly: false,
    allowFamilyMember: true,
    specialInstructionsEnabled: true,
    waitlistEnabled: true,
  },
  {
    id: 'cat-learn-test-prep-adult',
    name: 'Adult & Graduate Exams',
    icon: 'Briefcase',
    displayOrder: 32,
    isActive: true,
    catalogSlug: 'learn',
    description: 'GRE, GMAT, GED, HiSET, and ASVAB preparation.',
    requiresAttendee: false,
    membersOnly: false,
    allowFamilyMember: false,
    specialInstructionsEnabled: true,
    waitlistEnabled: false,
  },
  {
    id: 'cat-learn-enrichment-technology',
    name: 'Technology & Logic',
    icon: 'Cpu',
    displayOrder: 33,
    isActive: true,
    catalogSlug: 'learn',
    description: 'Coding, robotics, and chess — logic and problem-solving beyond the classroom.',
    requiresAttendee: false,
    membersOnly: false,
    allowFamilyMember: true,
    specialInstructionsEnabled: true,
    waitlistEnabled: true,
  },
  {
    id: 'cat-learn-enrichment-life-skills',
    name: 'Life Skills',
    icon: 'Lightbulb',
    displayOrder: 34,
    isActive: true,
    catalogSlug: 'learn',
    description: 'Financial literacy, public speaking, and debate for real-world confidence.',
    requiresAttendee: false,
    membersOnly: false,
    allowFamilyMember: true,
    specialInstructionsEnabled: true,
    waitlistEnabled: true,
  },
  {
    id: 'cat-learn-enrichment-arts',
    name: 'Arts & Creative',
    icon: 'Palette',
    displayOrder: 35,
    isActive: true,
    catalogSlug: 'learn',
    description: 'Creative writing and digital art workshops for young storytellers and designers.',
    requiresAttendee: false,
    membersOnly: false,
    allowFamilyMember: true,
    specialInstructionsEnabled: true,
    waitlistEnabled: true,
  },
]

const LEARN_CATEGORY_BY_ID = new Map(
  learnSchedulingCategories.map((category) => [category.id, category]),
)

const learnServiceSeeds: LearnServiceSeed[] = [
  {
    id: 'svc-learn-early-literacy',
    categoryId: 'cat-learn-elementary',
    serviceType: 'TUTORING_SESSION',
    name: 'Early Literacy — Phonics & Decoding',
    description:
      'Orton-Gillingham-inspired phonics, decoding, and sight-word fluency for emerging readers.',
    gradeLevel: 'K-2',
    subjectArea: 'Literacy',
    learningFormat: 'small-group',
    programTerm: 'Fall',
    programYear: 2026,
    programStartDate: '2026-09-02',
    programEndDate: '2027-06-12',
    instructorName: 'Dr. Emily Carter',
    basePrice: 65,
    capacity: 4,
    durationMinutes: 60,
    trialSessionAvailable: true,
    trialSessionPrice: 35,
    schedule: [
      { dayOfWeek: 'Tuesday', startTime: '4:00 PM', endTime: '5:00 PM' },
      { dayOfWeek: 'Thursday', startTime: '4:00 PM', endTime: '5:00 PM' },
    ],
  },
  {
    id: 'svc-learn-math-foundations',
    categoryId: 'cat-learn-elementary',
    serviceType: 'TUTORING_SESSION',
    name: 'Elementary Math Foundations',
    description:
      'Number sense, addition/subtraction fluency, and multiplication tables for grades 3–5.',
    gradeLevel: '3-5',
    subjectArea: 'Math',
    learningFormat: 'small-group',
    programTerm: 'Fall',
    programYear: 2026,
    programStartDate: '2026-09-02',
    programEndDate: '2027-06-12',
    instructorName: 'Marcus Webb',
    basePrice: 60,
    capacity: 6,
    durationMinutes: 60,
    schedule: [
      { dayOfWeek: 'Monday', startTime: '4:30 PM', endTime: '5:30 PM' },
      { dayOfWeek: 'Wednesday', startTime: '4:30 PM', endTime: '5:30 PM' },
    ],
  },
  {
    id: 'svc-learn-handwriting',
    categoryId: 'cat-learn-elementary',
    serviceType: 'TUTORING_SESSION',
    name: 'Handwriting — Print & Cursive',
    description: 'Legibility coaching for print and cursive writing.',
    gradeLevel: '3-5',
    subjectArea: 'Writing',
    learningFormat: 'small-group',
    programTerm: 'Year-Round',
    programYear: 2026,
    programStartDate: '2026-01-06',
    programEndDate: '2026-12-18',
    instructorName: 'Lisa Nguyen',
    basePrice: 45,
    capacity: 5,
    durationMinutes: 45,
    schedule: [{ dayOfWeek: 'Saturday', startTime: '10:00 AM', endTime: '10:45 AM' }],
  },
  {
    id: 'svc-learn-homework-club',
    categoryId: 'cat-learn-elementary',
    serviceType: 'TUTORING_SESSION',
    name: 'Homework Club',
    description: 'Supervised drop-in hours for homework completion and study habits.',
    gradeLevel: 'All',
    subjectArea: 'Other',
    learningFormat: 'group',
    programTerm: 'Year-Round',
    programYear: 2026,
    programStartDate: '2026-01-06',
    programEndDate: '2026-12-18',
    instructorName: 'Staff Tutors',
    basePrice: 25,
    capacity: 12,
    durationMinutes: 90,
    schedule: [
      { dayOfWeek: 'Monday – Thursday', startTime: '3:30 PM', endTime: '5:00 PM' },
    ],
  },
  {
    id: 'svc-learn-pre-algebra',
    categoryId: 'cat-learn-middle',
    serviceType: 'TUTORING_SESSION',
    name: 'Pre-Algebra & Algebra I',
    description: 'Core middle-school math — the most requested subject for ages 11–14.',
    gradeLevel: '6-8',
    subjectArea: 'Math',
    learningFormat: 'small-group',
    programTerm: 'Fall',
    programYear: 2026,
    programStartDate: '2026-09-02',
    programEndDate: '2027-06-12',
    instructorName: 'James Okonkwo',
    basePrice: 75,
    capacity: 6,
    durationMinutes: 60,
    schedule: [
      { dayOfWeek: 'Tuesday', startTime: '5:00 PM', endTime: '6:00 PM' },
      { dayOfWeek: 'Thursday', startTime: '5:00 PM', endTime: '6:00 PM' },
    ],
  },
  {
    id: 'svc-learn-essay-writing',
    categoryId: 'cat-learn-middle',
    serviceType: 'TUTORING_SESSION',
    name: 'Essay Writing Workshop',
    description: 'Structured five-paragraph essays, thesis statements, and revision skills.',
    gradeLevel: '6-8',
    subjectArea: 'Writing',
    learningFormat: 'workshop',
    programTerm: 'Spring',
    programYear: 2027,
    programStartDate: '2027-01-12',
    programEndDate: '2027-05-22',
    instructorName: 'Rachel Stein',
    basePrice: 70,
    capacity: 8,
    durationMinutes: 75,
    schedule: [{ dayOfWeek: 'Wednesday', startTime: '4:30 PM', endTime: '5:45 PM' }],
  },
  {
    id: 'svc-learn-general-science',
    categoryId: 'cat-learn-middle',
    serviceType: 'TUTORING_SESSION',
    name: 'General Science',
    description: 'Earth science and intro biology/chemistry concepts for middle schoolers.',
    gradeLevel: '6-8',
    subjectArea: 'Science',
    learningFormat: 'small-group',
    programTerm: 'Fall',
    programYear: 2026,
    programStartDate: '2026-09-02',
    programEndDate: '2027-06-12',
    instructorName: 'Dr. Priya Sharma',
    basePrice: 68,
    capacity: 6,
    durationMinutes: 60,
    schedule: [{ dayOfWeek: 'Monday', startTime: '5:00 PM', endTime: '6:00 PM' }],
  },
  {
    id: 'svc-learn-executive-functioning',
    categoryId: 'cat-learn-middle',
    serviceType: 'TUTORING_SESSION',
    name: 'Executive Functioning & Study Skills',
    description: 'Organization, planner use, and focus strategies for ADHD and disorganization.',
    gradeLevel: '6-8',
    subjectArea: 'Life Skills',
    learningFormat: 'individual',
    programTerm: 'Year-Round',
    programYear: 2026,
    programStartDate: '2026-01-06',
    programEndDate: '2026-12-18',
    instructorName: 'Alex Morgan',
    basePrice: 95,
    capacity: 1,
    durationMinutes: 50,
    schedule: [{ dayOfWeek: 'By appointment', startTime: 'Flexible', endTime: 'Flexible' }],
  },
  {
    id: 'svc-learn-stem-track',
    categoryId: 'cat-learn-high-school',
    serviceType: 'TUTORING_SESSION',
    name: 'STEM Track — Geometry through Calculus',
    description: 'Geometry, Algebra II, Pre-Calc, and AP Calculus AB/BC support.',
    gradeLevel: '9-12',
    subjectArea: 'Math',
    learningFormat: 'small-group',
    programTerm: 'Fall',
    programYear: 2026,
    programStartDate: '2026-09-02',
    programEndDate: '2027-06-12',
    instructorName: 'Dr. Thomas Reed',
    basePrice: 85,
    capacity: 5,
    durationMinutes: 90,
    schedule: [
      { dayOfWeek: 'Tuesday', startTime: '6:00 PM', endTime: '7:30 PM' },
      { dayOfWeek: 'Thursday', startTime: '6:00 PM', endTime: '7:30 PM' },
    ],
  },
  {
    id: 'svc-learn-humanities-track',
    categoryId: 'cat-learn-high-school',
    serviceType: 'TUTORING_SESSION',
    name: 'Humanities Track — History & AP English',
    description: 'U.S. History, World History, Government, and AP English Language/Literature.',
    gradeLevel: '9-12',
    subjectArea: 'History',
    learningFormat: 'small-group',
    programTerm: 'Fall',
    programYear: 2026,
    programStartDate: '2026-09-02',
    programEndDate: '2027-06-12',
    instructorName: 'Margaret Hayes',
    basePrice: 80,
    capacity: 6,
    durationMinutes: 75,
    schedule: [{ dayOfWeek: 'Wednesday', startTime: '6:00 PM', endTime: '7:15 PM' }],
  },
  {
    id: 'svc-learn-foreign-language',
    categoryId: 'cat-learn-high-school',
    serviceType: 'TUTORING_SESSION',
    name: 'Foreign Language — Spanish, French, Mandarin',
    description: 'Grammar, conversation, and exam prep for high-school language courses.',
    gradeLevel: '9-12',
    subjectArea: 'Foreign Language',
    learningFormat: 'small-group',
    programTerm: 'Year-Round',
    programYear: 2026,
    programStartDate: '2026-01-06',
    programEndDate: '2026-12-18',
    instructorName: 'Sofia Delgado',
    basePrice: 72,
    capacity: 5,
    durationMinutes: 60,
    schedule: [{ dayOfWeek: 'Saturday', startTime: '11:00 AM', endTime: '12:00 PM' }],
  },
  {
    id: 'svc-learn-sat-act-bootcamp',
    categoryId: 'cat-learn-test-prep-college',
    serviceType: 'TEST_PREP',
    name: 'SAT / ACT Bootcamp',
    description: '6–8 week intensive covering strategies, timed practice, and full mock exams.',
    gradeLevel: '9-12',
    subjectArea: 'Test Prep',
    learningFormat: 'bootcamp',
    programTerm: 'Summer',
    programYear: 2026,
    programStartDate: '2026-06-08',
    programEndDate: '2026-08-01',
    instructorName: 'Kevin Park',
    basePrice: 120,
    capacity: 12,
    durationMinutes: 120,
    schedule: [
      { dayOfWeek: 'Monday – Thursday', startTime: '9:00 AM', endTime: '11:00 AM' },
    ],
  },
  {
    id: 'svc-learn-college-essay',
    categoryId: 'cat-learn-test-prep-college',
    serviceType: 'TEST_PREP',
    name: 'College Essay Writing Bootcamp',
    description: 'August/September intensive to draft and polish personal statements.',
    gradeLevel: '9-12',
    subjectArea: 'Writing',
    learningFormat: 'bootcamp',
    programTerm: 'Fall',
    programYear: 2026,
    programStartDate: '2026-08-10',
    programEndDate: '2026-09-15',
    instructorName: 'Rachel Stein',
    basePrice: 150,
    capacity: 8,
    durationMinutes: 90,
    schedule: [
      { dayOfWeek: 'Tuesday & Thursday', startTime: '5:00 PM', endTime: '6:30 PM' },
    ],
  },
  {
    id: 'svc-learn-isee-ssat',
    categoryId: 'cat-learn-test-prep-private-school',
    serviceType: 'TEST_PREP',
    name: 'ISEE / SSAT Prep',
    description: 'Private high-school entrance exam prep for elementary and middle applicants.',
    gradeLevel: '3-5',
    subjectArea: 'Test Prep',
    learningFormat: 'small-group',
    programTerm: 'Fall',
    programYear: 2026,
    programStartDate: '2026-09-02',
    programEndDate: '2026-12-15',
    instructorName: 'Kevin Park',
    basePrice: 90,
    capacity: 6,
    durationMinutes: 75,
    schedule: [{ dayOfWeek: 'Saturday', startTime: '9:00 AM', endTime: '10:15 AM' }],
  },
  {
    id: 'svc-learn-hspt-coop',
    categoryId: 'cat-learn-test-prep-private-school',
    serviceType: 'TEST_PREP',
    name: 'HSPT / COOP Prep',
    description: 'Catholic high school entrance exam prep — verbal, math, and timed practice.',
    gradeLevel: '6-8',
    subjectArea: 'Test Prep',
    learningFormat: 'small-group',
    programTerm: 'Fall',
    programYear: 2026,
    programStartDate: '2026-09-02',
    programEndDate: '2026-12-15',
    instructorName: 'Margaret Hayes',
    basePrice: 88,
    capacity: 8,
    durationMinutes: 75,
    schedule: [{ dayOfWeek: 'Saturday', startTime: '10:30 AM', endTime: '11:45 AM' }],
  },
  {
    id: 'svc-learn-gre-gmat',
    categoryId: 'cat-learn-test-prep-adult',
    serviceType: 'TEST_PREP',
    name: 'GRE / GMAT Prep',
    description: 'Graduate and business school entrance exam preparation for adults.',
    gradeLevel: 'Adult',
    subjectArea: 'Test Prep',
    learningFormat: 'small-group',
    programTerm: 'Year-Round',
    programYear: 2026,
    programStartDate: '2026-01-06',
    programEndDate: '2026-12-18',
    instructorName: 'Dr. Thomas Reed',
    basePrice: 110,
    capacity: 8,
    durationMinutes: 90,
    schedule: [{ dayOfWeek: 'Wednesday', startTime: '7:00 PM', endTime: '8:30 PM' }],
  },
  {
    id: 'svc-learn-ged-hiset',
    categoryId: 'cat-learn-test-prep-adult',
    serviceType: 'TEST_PREP',
    name: 'GED / HiSET Equivalency',
    description: 'High school equivalency exam preparation.',
    gradeLevel: 'Adult',
    subjectArea: 'Test Prep',
    learningFormat: 'group',
    programTerm: 'Year-Round',
    programYear: 2026,
    programStartDate: '2026-01-06',
    programEndDate: '2026-12-18',
    instructorName: 'Marcus Webb',
    basePrice: 55,
    capacity: 10,
    durationMinutes: 90,
    schedule: [{ dayOfWeek: 'Tuesday & Thursday', startTime: '6:30 PM', endTime: '8:00 PM' }],
  },
  {
    id: 'svc-learn-asvab',
    categoryId: 'cat-learn-test-prep-adult',
    serviceType: 'TEST_PREP',
    name: 'ASVAB Prep',
    description: 'Armed Services Vocational Aptitude Battery — math, verbal, and career field review.',
    gradeLevel: 'Adult',
    subjectArea: 'Test Prep',
    learningFormat: 'small-group',
    programTerm: 'Year-Round',
    programYear: 2026,
    programStartDate: '2026-01-06',
    programEndDate: '2026-12-18',
    instructorName: 'James Okonkwo',
    basePrice: 65,
    capacity: 10,
    durationMinutes: 90,
    schedule: [{ dayOfWeek: 'Saturday', startTime: '9:00 AM', endTime: '10:30 AM' }],
  },
  {
    id: 'svc-learn-coding-kids',
    categoryId: 'cat-learn-enrichment-technology',
    serviceType: 'ENRICHMENT_CLASS',
    name: 'Coding for Kids',
    description: 'Python, Java, or Scratch visual coding for beginners through intermediate learners.',
    gradeLevel: '3-5',
    subjectArea: 'Technology',
    learningFormat: 'workshop',
    programTerm: 'Fall',
    programYear: 2026,
    programStartDate: '2026-09-02',
    programEndDate: '2027-06-12',
    instructorName: 'Jordan Lee',
    basePrice: 55,
    capacity: 10,
    durationMinutes: 75,
    schedule: [{ dayOfWeek: 'Saturday', startTime: '1:00 PM', endTime: '2:15 PM' }],
  },
  {
    id: 'svc-learn-robotics',
    categoryId: 'cat-learn-enrichment-technology',
    serviceType: 'ENRICHMENT_CLASS',
    name: 'Robotics Club',
    description: 'LEGO Mindstorms or VEX robotics clubs — build, code, and compete as a team.',
    gradeLevel: '6-8',
    subjectArea: 'Technology',
    learningFormat: 'group',
    programTerm: 'Fall',
    programYear: 2026,
    programStartDate: '2026-09-02',
    programEndDate: '2027-06-12',
    instructorName: 'Jordan Lee',
    basePrice: 65,
    capacity: 8,
    durationMinutes: 90,
    schedule: [{ dayOfWeek: 'Friday', startTime: '4:00 PM', endTime: '5:30 PM' }],
  },
  {
    id: 'svc-learn-chess-club',
    categoryId: 'cat-learn-enrichment-technology',
    serviceType: 'ENRICHMENT_CLASS',
    name: 'Chess Club',
    description: 'Teaches logic and strategy for all skill levels, from first moves to tournament play.',
    gradeLevel: 'All',
    subjectArea: 'Technology',
    learningFormat: 'group',
    programTerm: 'Year-Round',
    programYear: 2026,
    programStartDate: '2026-01-06',
    programEndDate: '2026-12-18',
    instructorName: 'Grandmaster Chen',
    basePrice: 35,
    capacity: 16,
    durationMinutes: 60,
    schedule: [{ dayOfWeek: 'Wednesday', startTime: '5:30 PM', endTime: '6:30 PM' }],
  },
  {
    id: 'svc-learn-financial-literacy',
    categoryId: 'cat-learn-enrichment-life-skills',
    serviceType: 'ENRICHMENT_CLASS',
    name: 'Financial Literacy',
    description: 'Budgeting, understanding credit, and basic investing for teens.',
    gradeLevel: '9-12',
    subjectArea: 'Life Skills',
    learningFormat: 'workshop',
    programTerm: 'Spring',
    programYear: 2027,
    programStartDate: '2027-01-12',
    programEndDate: '2027-05-22',
    instructorName: 'Alex Morgan',
    basePrice: 50,
    capacity: 12,
    durationMinutes: 60,
    schedule: [{ dayOfWeek: 'Thursday', startTime: '5:00 PM', endTime: '6:00 PM' }],
  },
  {
    id: 'svc-learn-public-speaking',
    categoryId: 'cat-learn-enrichment-life-skills',
    serviceType: 'ENRICHMENT_CLASS',
    name: 'Public Speaking & Debate',
    description: 'Building confidence and presentation skills through structured debate.',
    gradeLevel: '6-8',
    subjectArea: 'Life Skills',
    learningFormat: 'workshop',
    programTerm: 'Fall',
    programYear: 2026,
    programStartDate: '2026-09-02',
    programEndDate: '2027-06-12',
    instructorName: 'Margaret Hayes',
    basePrice: 58,
    capacity: 10,
    durationMinutes: 75,
    schedule: [{ dayOfWeek: 'Monday', startTime: '5:30 PM', endTime: '6:45 PM' }],
  },
  {
    id: 'svc-learn-creative-writing',
    categoryId: 'cat-learn-enrichment-arts',
    serviceType: 'ENRICHMENT_CLASS',
    name: 'Creative Writing',
    description: 'Fiction, poetry, and screenwriting groups in a supportive peer workshop.',
    gradeLevel: '9-12',
    subjectArea: 'Arts',
    learningFormat: 'workshop',
    programTerm: 'Year-Round',
    programYear: 2026,
    programStartDate: '2026-01-06',
    programEndDate: '2026-12-18',
    instructorName: 'Rachel Stein',
    basePrice: 48,
    capacity: 8,
    durationMinutes: 75,
    schedule: [{ dayOfWeek: 'Tuesday', startTime: '6:00 PM', endTime: '7:15 PM' }],
  },
  {
    id: 'svc-learn-digital-art',
    categoryId: 'cat-learn-enrichment-arts',
    serviceType: 'ENRICHMENT_CLASS',
    name: 'Digital Art & Graphic Design',
    description: 'Introduction to Adobe Photoshop or Canva for young creators.',
    gradeLevel: '9-12',
    subjectArea: 'Arts',
    learningFormat: 'workshop',
    programTerm: 'Summer',
    programYear: 2026,
    programStartDate: '2026-06-08',
    programEndDate: '2026-08-01',
    instructorName: 'Sofia Delgado',
    basePrice: 62,
    capacity: 8,
    durationMinutes: 90,
    schedule: [{ dayOfWeek: 'Saturday', startTime: '2:00 PM', endTime: '3:30 PM' }],
  },
]

function buildLearnService(seed: LearnServiceSeed): SchedulingService {
  const category = LEARN_CATEGORY_BY_ID.get(seed.categoryId)
  if (!category) {
    throw new Error(`Missing learn category: ${seed.categoryId}`)
  }

  return {
    id: seed.id,
    locationId: 'loc-1',
    categoryId: seed.categoryId,
    category: { ...category },
    serviceType: seed.serviceType,
    bookingMode: 'SCHEDULED',
    name: seed.name,
    description: seed.description,
    durationMinutes: seed.durationMinutes,
    capacity: seed.capacity,
    basePrice: seed.basePrice,
    subscriptionPrice: null,
    requiresWaiver: false,
    ageMin: null,
    ageMax: null,
    isActive: true,
    minDurationMinutes: null,
    maxDurationMinutes: null,
    slotIncrementMinutes: null,
    maxConcurrent: null,
    minAdvanceHours: 24,
    maxAdvanceHours: 2160,
    pricingModel: 'per_person',
    imageUrl:
      seed.imageUrl ??
      'https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=1200&q=80',
    tags: ['learn', seed.subjectArea.toLowerCase().replace(/\s+/g, '-')],
    instructorName: seed.instructorName,
    schedule: seed.schedule.map((entry) => ({ ...entry })),
    gradeLevel: seed.gradeLevel,
    subjectArea: seed.subjectArea,
    learningFormat: seed.learningFormat,
    programTerm: seed.programTerm,
    programYear: seed.programYear,
    programStartDate: LEARN_MOCK_PROGRAM_START_DATE,
    programEndDate: LEARN_MOCK_PROGRAM_END_DATE,
    trialSessionAvailable: seed.trialSessionAvailable ?? false,
    trialSessionPrice: seed.trialSessionPrice ?? null,
    level: 'All Levels',
    eventBookingScheduleMode: EventBookingScheduleModeEnum.PER_EVENT,
  }
}

export const learnSectionServices: SchedulingService[] = learnServiceSeeds.map(buildLearnService)
